// <auto-generated />
using System;
using Fluxo.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fluxo.Data.Migrations
{
    [DbContext(typeof(FluxoDbContext))]
    partial class FluxoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Fluxo.Core.Entities.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpenseCategory")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExpenseKind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExpenseTagId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RecurringDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SpendingSourceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseTagId");

                    b.HasIndex("SpendingSourceId");

                    b.ToTable("Expenses", (string)null);
                });

            modelBuilder.Entity("Fluxo.Core.Entities.ExpenseLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DeductedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpenseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SpendingSourceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseId");

                    b.HasIndex("SpendingSourceId");

                    b.ToTable("ExpenseLogs", (string)null);
                });

            modelBuilder.Entity("Fluxo.Core.Entities.ExpenseTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HexCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ExpenseTags", (string)null);
                });

            modelBuilder.Entity("Fluxo.Core.Entities.SavingGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CurrentAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SavingEndDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SavingGoals", (string)null);
                });

            modelBuilder.Entity("Fluxo.Core.Entities.SpendingSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("InterestRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Limit")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SpendingSourceType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SpentAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SpendingSources", (string)null);
                });

            modelBuilder.Entity("Fluxo.Core.Entities.Expense", b =>
                {
                    b.HasOne("Fluxo.Core.Entities.ExpenseTag", "ExpenseTag")
                        .WithMany()
                        .HasForeignKey("ExpenseTagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fluxo.Core.Entities.SpendingSource", "SpendingSource")
                        .WithMany()
                        .HasForeignKey("SpendingSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExpenseTag");

                    b.Navigation("SpendingSource");
                });

            modelBuilder.Entity("Fluxo.Core.Entities.ExpenseLog", b =>
                {
                    b.HasOne("Fluxo.Core.Entities.Expense", "Expense")
                        .WithMany()
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fluxo.Core.Entities.SpendingSource", "SpendingSource")
                        .WithMany()
                        .HasForeignKey("SpendingSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Expense");

                    b.Navigation("SpendingSource");
                });
#pragma warning restore 612, 618
        }
    }
}
