// <auto-generated />
using System;
using Fluxo.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fluxo.Migrations
{
    [DbContext(typeof(FluxoDbContext))]
    [Migration("20260811121505_ReplaceBudgetExclusionWithExcludedCategory")]
    partial class ReplaceBudgetExclusionWithExcludedCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Fluxo.Core.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AccountLimit")
                        .HasColumnType("NUMERIC");

                    b.Property<int>("AccountType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasColumnType("NUMERIC");

                    b.Property<int?>("DeductSource")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("InterestRate")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsForDeletion")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaximumSpending")
                        .HasColumnType("NUMERIC");

                    b.Property<decimal?>("MinimumPayment")
                        .HasColumnType("NUMERIC");

                    b.Property<int?>("MonthlyDueDate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("PinnedOnUI")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SpentAmount")
                        .HasColumnType("NUMERIC");

                    b.HasKey("Id");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasFilter("IsDefault = 1");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("Fluxo.Core.Entities.BudgetAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AllocationLimit")
                        .HasColumnType("NUMERIC");

                    b.Property<int>("AllocationPeriod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentPeriodIndex")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("InvestDebt")
                        .HasColumnType("NUMERIC");

                    b.Property<int>("InvestThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastRolloverPeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NeedsDebt")
                        .HasColumnType("NUMERIC");

                    b.Property<int>("NeedsThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OverspendPolicy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PeriodStart")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RolloverPolicy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SingletonKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<decimal>("WantsDebt")
                        .HasColumnType("NUMERIC");

                    b.Property<int>("WantsThreshold")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SingletonKey")
                        .IsUnique();

                    b.ToTable("BudgetAllocation", (string)null);
                });

            modelBuilder.Entity("Fluxo.Core.Entities.RecurringTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("NUMERIC");

                    b.Property<int?>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GoalId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RecurringPeriod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecurringTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TagId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.HasIndex("SourceId");

                    b.HasIndex("TagId");

                    b.ToTable("RecurringTransactions", (string)null);
                });

            modelBuilder.Entity("Fluxo.Core.Entities.SavingGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentAmount")
                        .HasColumnType("NUMERIC");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SavingEndDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("NUMERIC");

                    b.HasKey("Id");

                    b.ToTable("SavingGoals", (string)null);
                });

            modelBuilder.Entity("Fluxo.Core.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HexCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSystemTag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SpendingLimit")
                        .HasColumnType("NUMERIC");

                    b.HasKey("Id");

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("Fluxo.Core.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("NUMERIC");

                    b.Property<int?>("ExpenseCategory")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GoalId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsForDeletion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsIoU")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPinned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LoggedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentTransactionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RelatedRecurringTransactionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RepaymentAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShouldAffectBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("SourceAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TagId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.HasIndex("ParentTransactionId");

                    b.HasIndex("RelatedRecurringTransactionId");

                    b.HasIndex("RepaymentAccountId");

                    b.HasIndex("SourceAccountId");

                    b.HasIndex("TagId");

                    b.ToTable("Transactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Transactions_Amount", "Amount >= 0");

                            t.HasCheckConstraint("CK_Transactions_ShouldAffectBalance_RequiresIoU", "ShouldAffectBalance = 0 OR IsIoU = 1");
                        });
                });

            modelBuilder.Entity("Fluxo.Core.Entities.UserSettings", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("UserSettings", (string)null);
                });

            modelBuilder.Entity("Fluxo.Core.Entities.RecurringTransaction", b =>
                {
                    b.HasOne("Fluxo.Core.Entities.SavingGoal", "Goal")
                        .WithMany()
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fluxo.Core.Entities.Account", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fluxo.Core.Entities.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Goal");

                    b.Navigation("Source");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Fluxo.Core.Entities.Transaction", b =>
                {
                    b.HasOne("Fluxo.Core.Entities.SavingGoal", "Goal")
                        .WithMany()
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fluxo.Core.Entities.Transaction", "ParentTransaction")
                        .WithMany()
                        .HasForeignKey("ParentTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fluxo.Core.Entities.RecurringTransaction", "RelatedRecurringTransaction")
                        .WithMany()
                        .HasForeignKey("RelatedRecurringTransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fluxo.Core.Entities.Account", "RepaymentAccount")
                        .WithMany()
                        .HasForeignKey("RepaymentAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fluxo.Core.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("SourceAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fluxo.Core.Entities.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Account");

                    b.Navigation("Goal");

                    b.Navigation("ParentTransaction");

                    b.Navigation("RelatedRecurringTransaction");

                    b.Navigation("RepaymentAccount");

                    b.Navigation("Tag");
                });
#pragma warning restore 612, 618
        }
    }
}
